FROM ckan/ckan-dev:2.10.3

# Copy custom initialization scripts
COPY docker-entrypoint.d/* /docker-entrypoint.d/

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY patches ${APP_DIR}/patches

RUN apk add gnupg
# Agregar el script para instalar el controlador ODBC y las herramientas de MSSQL
COPY install_mssql_tools.sh /usr/local/bin/

# Cambiar los permisos del script para que sea ejecutable
RUN chmod +x /usr/local/bin/install_mssql_tools.sh

# Ejecutar el script para instalar el controlador ODBC y las herramientas de MSSQL
RUN /usr/local/bin/install_mssql_tools.sh

RUN apk update
RUN apk add gcc libc-dev g++ libffi-dev libxml2 unixodbc-dev mariadb-dev
RUN apk add build-base freetds-dev
RUN apk add --no-cache python3 py3-pip

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done
